name: Conventional PR

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  conventional-pr:
    uses: thaim/actions/.github/workflows/reusable-conventional-pr.yml@4a149f95d26f73b47424ff7b4652bf70b548cac6 # v1.4.0
